%========================================================================
% CryoGrid INIT_STEADY_STATE class INIT_TTOP_from_out
% CryoGrid INIT_STEADY_STATE class used in conjcntion with the TILE_BUILDER
% class new_init_steady_state; reads the temperature on the top of 
% permafrost (TTOP) and the maximum depth of the permafrost table from an 
% existing OUT file written by the class OUT_TDD_FDD. 
% It is used in the accelerated spin-up procedure.

% S. Westermann, Jan 2022
%========================================================================


classdef INIT_TTOP_from_out < matlab.mixin.Copyable
 

    properties
        PARA
        CONST
        STATVAR
	end
    
    
    methods

        
        function init = provide_PARA(init)         

            init.PARA.out_folder = []; %if empty, use the result folder
            init.PARA.out_file = [];

        end
        
        function init = provide_CONST(init)

        end
        
        function init = provide_STATVAR(init)

        end

		function init = finalize_init(init, tile)
             if isempty(init.PARA.out_folder) || sum(isnan(init.PARA.out_folder))>0
                 init.PARA.out_folder = [tile.PARA.result_path tile.PARA.run_name '/'];
                 init.PARA.out_file = [tile.PARA.run_name '_OUT_FDD_TDD.mat'];
             end
             temp=load([init.PARA.out_folder init.PARA.out_file], 'out');
             out = temp.out;
             tile.PARA.T_first_cell = out.STATVAR.TTOP;
             tile.PARA.start_depth_steady_state = out.STATVAR.TTOP_depth;
        end
        
        
        
        %-------------param file generation-----
        function init = param_file_info(init)
            init = provide_PARA(init);

            init.PARA.STATVAR = [];
            init.PARA.options = [];
            init.PARA.class_category = 'init_steady_state';
            
            init.PARA.default_value.out_file = {''};
            init.PARA.comment.out_file = {'if empty, use the default file name generated by OUT_FDD_TDD'};
            
            init.PARA.default_value.out_folder = {''};
            init.PARA.comment.out_folder = {'if empty, use the result folder'};
            
        end
        

    end
end