@startuml
    skinparam {
    }
    title
        <font color=Maroon size=18>Inheritance map for FORCING classes</font>
    end title
    class FORCING_read_out <<(V,PaleGreen)>> [[matlab:matlab.desktop.editor.openAndGoToLine('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\FORCING\FORCING_read_out.m',7);{No tooltip}]] {
        {field} + DATA [[[matlab:matlab.desktop.editor.openAndGoToLine('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\FORCING\FORCING_read_out.m',11);{No tooltip}]]]
        {field} + forcing_index [[[matlab:matlab.desktop.editor.openAndGoToLine('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\FORCING\FORCING_read_out.m',10);{No tooltip}]]]
        {field} + PARA [[[matlab:matlab.desktop.editor.openAndGoToLine('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\FORCING\FORCING_read_out.m',13);{No tooltip}]]]
        {field} + STATUS [[[matlab:matlab.desktop.editor.openAndGoToLine('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\FORCING\FORCING_read_out.m',14);{No tooltip}]]]
        {field} + TEMP [[[matlab:matlab.desktop.editor.openAndGoToLine('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\FORCING\FORCING_read_out.m',12);{No tooltip}]]]
        ---
        {method} + FORCING_read_out  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\FORCING\FORCING_read_out.m','FORCING_read_out');{function self = FORCING_seb(index, pprovider, fprovider)      % Definition to be used when old code is no longer supported}]]]
        {method} + finalize_setup  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\FORCING\FORCING_read_out.m','finalize_setup');{No tooltip}]]]
        {method} + initialize  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\FORCING\FORCING_read_out.m','initialize');{INITIALIZE  Initializes all properties needed by the class.}]]]
        {method} + initialize_DATA  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\FORCING\FORCING_read_out.m','initialize_DATA');{INITIALIZE_DATA  Initializes DATA structure.}]]]
        {method} + initialize_PARA  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\FORCING\FORCING_read_out.m','initialize_PARA');{INITIALIZE_PARA  Initializes PARA structure, setting the variables in PARA.}]]]
        {method} + initialize_TEMP  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\FORCING\FORCING_read_out.m','initialize_TEMP');{INITIALIZE_TEMP  Initializes TEMP structure.}]]]
        {method} + interpolate_forcing  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\FORCING\FORCING_read_out.m','interpolate_forcing');{No tooltip}]]]
        {method} + load_forcing_from_mat  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\FORCING\FORCING_read_out.m','load_forcing_from_mat');{No tooltip}]]]
        {method} + populate_DATA  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\FORCING\FORCING_read_out.m','populate_DATA');{POPULATE_DATA  Updates the DATA structure with values from fprovider.}]]]
        {method} + populate_PARA  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\FORCING\FORCING_read_out.m','populate_PARA');{POPULATE_PARA  Updates the PARA structure with values from pprovider.}]]]
    }
    class FORCING_seb <<(V,PaleGreen)>> [[matlab:matlab.desktop.editor.openAndGoToLine('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\FORCING\@FORCING_seb\FORCING_seb.m',29);{No tooltip}]] {
        {field} + DATA [[[matlab:matlab.desktop.editor.openAndGoToLine('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\FORCING\@FORCING_seb\FORCING_seb.m',33);{No tooltip}]]]
        {field} + forcing_index [[[matlab:matlab.desktop.editor.openAndGoToLine('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\FORCING\@FORCING_seb\FORCING_seb.m',32);{No tooltip}]]]
        {field} + PARA [[[matlab:matlab.desktop.editor.openAndGoToLine('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\FORCING\@FORCING_seb\FORCING_seb.m',35);{No tooltip}]]]
        {field} + STATUS [[[matlab:matlab.desktop.editor.openAndGoToLine('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\FORCING\@FORCING_seb\FORCING_seb.m',36);{No tooltip}]]]
        {field} + TEMP [[[matlab:matlab.desktop.editor.openAndGoToLine('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\FORCING\@FORCING_seb\FORCING_seb.m',34);{No tooltip}]]]
        ---
        {method} + FORCING_seb  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\FORCING\@FORCING_seb\FORCING_seb.m','FORCING_seb');{}]]]
        {method} + finalize_setup  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\FORCING\@FORCING_seb\FORCING_seb.m','finalize_setup');{}]]]
        {method} + initialize  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\FORCING\@FORCING_seb\FORCING_seb.m','initialize');{}]]]
        {method} + initialize_DATA  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\FORCING\@FORCING_seb\FORCING_seb.m','initialize_DATA');{}]]]
        {method} + initialize_PARA  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\FORCING\@FORCING_seb\FORCING_seb.m','initialize_PARA');{}]]]
        {method} + initialize_TEMP  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\FORCING\@FORCING_seb\FORCING_seb.m','initialize_TEMP');{}]]]
        {method} + interpolate_forcing  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\FORCING\@FORCING_seb\FORCING_seb.m','interpolate_forcing');{}]]]
        {method} + load_forcing_from_mat  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\FORCING\@FORCING_seb\FORCING_seb.m','load_forcing_from_mat');{}]]]
        {method} + populate_DATA  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\FORCING\@FORCING_seb\FORCING_seb.m','populate_DATA');{}]]]
        {method} + populate_PARA  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\FORCING\@FORCING_seb\FORCING_seb.m','populate_PARA');{}]]]
        {method} + write_excel  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\FORCING\@FORCING_seb\FORCING_seb.m','write_excel');{}]]]
    }
    class FORCING_seb_salt <<(V,PaleGreen)>> [[matlab:matlab.desktop.editor.openAndGoToLine('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\FORCING\@FORCING_seb_salt\FORCING_seb_salt.m',4);{No tooltip}]] {
        {field} + DATA [[[matlab:matlab.desktop.editor.openAndGoToLine('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\FORCING\@FORCING_seb_salt\FORCING_seb_salt.m',6);{No tooltip}]]]
        {field} + PARA [[[matlab:matlab.desktop.editor.openAndGoToLine('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\FORCING\@FORCING_seb_salt\FORCING_seb_salt.m',8);{No tooltip}]]]
        {field} + STATUS [[[matlab:matlab.desktop.editor.openAndGoToLine('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\FORCING\@FORCING_seb_salt\FORCING_seb_salt.m',9);{No tooltip}]]]
        {field} + TEMP [[[matlab:matlab.desktop.editor.openAndGoToLine('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\FORCING\@FORCING_seb_salt\FORCING_seb_salt.m',7);{No tooltip}]]]
        ---
        {method} + interpolate_forcing  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\FORCING\@FORCING_seb_salt\FORCING_seb_salt.m','interpolate_forcing');{}]]]
        {method} + load_forcing_from_mat  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\FORCING\@FORCING_seb_salt\FORCING_seb_salt.m','load_forcing_from_mat');{}]]]
        {method} + set_parameters  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\FORCING\@FORCING_seb_salt\FORCING_seb_salt.m','set_parameters');{}]]]
    }
@enduml
