@startuml
    skinparam {
    }
    title
        <font color=Maroon size=18>Inheritance map for SNOW_crocus_bucketW_seb</font>
    end title
    class BASE <<(H,#E6FFE6)>> [[matlab:matlab.desktop.editor.openAndGoToLine('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_0_base\BASE.m',6);{No tooltip}]] {
        {field} + class_index [[[matlab:matlab.desktop.editor.openAndGoToLine('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_0_base\BASE.m',9);{No tooltip}]]]
        {field} + CONST [[[matlab:matlab.desktop.editor.openAndGoToLine('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_0_base\BASE.m',10);{No tooltip}]]]
        {field} + IA_NEXT [[[matlab:matlab.desktop.editor.openAndGoToLine('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_0_base\BASE.m',17);{No tooltip}]]]
        {field} + IA_PREVIOUS [[[matlab:matlab.desktop.editor.openAndGoToLine('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_0_base\BASE.m',16);{No tooltip}]]]
        {field} + NEXT [[[matlab:matlab.desktop.editor.openAndGoToLine('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_0_base\BASE.m',15);{No tooltip}]]]
        {field} + PARA [[[matlab:matlab.desktop.editor.openAndGoToLine('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_0_base\BASE.m',11);{No tooltip}]]]
        {field} + PREVIOUS [[[matlab:matlab.desktop.editor.openAndGoToLine('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_0_base\BASE.m',14);{No tooltip}]]]
        {field} + STATVAR [[[matlab:matlab.desktop.editor.openAndGoToLine('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_0_base\BASE.m',12);{No tooltip}]]]
        {field} + TEMP [[[matlab:matlab.desktop.editor.openAndGoToLine('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_0_base\BASE.m',13);{No tooltip}]]]
        ---
        {method} + get_saturated_hardBottom_first_cell  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_0_base\BASE.m','get_saturated_hardBottom_first_cell');{No tooltip}]]]
        {method} + initialize_excel  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_0_base\BASE.m','initialize_excel');{No tooltip}]]]
        {method} + lateral3D_pull_heat  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_0_base\BASE.m','lateral3D_pull_heat');{No tooltip}]]]
        {method} + lateral3D_pull_water_general_aquifer  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_0_base\BASE.m','lateral3D_pull_water_general_aquifer');{No tooltip}]]]
        {method} + lateral3D_pull_water_unconfined_aquifer  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_0_base\BASE.m','lateral3D_pull_water_unconfined_aquifer');{No tooltip}]]]
        {method} + lateral3D_push_heat  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_0_base\BASE.m','lateral3D_push_heat');{No tooltip}]]]
        {method} + lateral3D_push_water_general_aquifer  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_0_base\BASE.m','lateral3D_push_water_general_aquifer');{No tooltip}]]]
        {method} + lateral3D_push_water_unconfined_aquifer  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_0_base\BASE.m','lateral3D_push_water_unconfined_aquifer');{No tooltip}]]]
        {method} + lateral_push_remove_subsurfaceWater  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_0_base\BASE.m','lateral_push_remove_subsurfaceWater');{No tooltip}]]]
        {method} + lateral_push_remove_surfaceWater  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_0_base\BASE.m','lateral_push_remove_surfaceWater');{No tooltip}]]]
        {method} + lateral_push_remove_water_seepage  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_0_base\BASE.m','lateral_push_remove_water_seepage');{No tooltip}]]]
        {method} + lateral_push_water_reservoir  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_0_base\BASE.m','lateral_push_water_reservoir');{No tooltip}]]]
    }
    class HEAT_CONDUCTION <<(H,#E6FFE6)>> [[matlab:matlab.desktop.editor.openAndGoToLine('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\HEAT_CONDUCTION.m',8);{No tooltip}]] {
        ---
        {method} + conductivity_mixing_squares  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\HEAT_CONDUCTION.m','conductivity_mixing_squares');{No tooltip}]]]
        {method} + conductivity_mixing_squares_Xice  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\HEAT_CONDUCTION.m','conductivity_mixing_squares_Xice');{No tooltip}]]]
        {method} + conductivity_snow_Yen  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\HEAT_CONDUCTION.m','conductivity_snow_Yen');{No tooltip}]]]
        {method} + get_derivative_energy  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\HEAT_CONDUCTION.m','get_derivative_energy');{No tooltip}]]]
        {method} + get_E_freeW  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\HEAT_CONDUCTION.m','get_E_freeW');{No tooltip}]]]
        {method} + get_T_water_freeW  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\HEAT_CONDUCTION.m','get_T_water_freeW');{No tooltip}]]]
        {method} + get_timestep_heat_coduction  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\HEAT_CONDUCTION.m','get_timestep_heat_coduction');{No tooltip}]]]
    }
    class HEAT_FLUXES_LATERAL <<(H,#E6FFE6)>> [[matlab:matlab.desktop.editor.openAndGoToLine('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\HEAT_FLUXES_LATERAL.m',8);{No tooltip}]] {
        ---
        {method} + lateral3D_pull_heat_simple  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\HEAT_FLUXES_LATERAL.m','lateral3D_pull_heat_simple');{No tooltip}]]]
        {method} + lateral3D_push_heat_simple  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\HEAT_FLUXES_LATERAL.m','lateral3D_push_heat_simple');{No tooltip}]]]
    }
    class REGRID <<(H,#E6FFE6)>> [[matlab:matlab.desktop.editor.openAndGoToLine('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\REGRID.m',6);{No tooltip}]] {
        ---
        {method} + merge_cells_extensive  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\REGRID.m','merge_cells_extensive');{No tooltip}]]]
        {method} + merge_cells_extensive2  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\REGRID.m','merge_cells_extensive2');{No tooltip}]]]
        {method} + merge_cells_intensive  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\REGRID.m','merge_cells_intensive');{weighted average, using scaling_variable as weighing function -> example:}]]]
        {method} + merge_cells_intensive2  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\REGRID.m','merge_cells_intensive2');{No tooltip}]]]
        {method} + regrid_full  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\REGRID.m','regrid_full');{No tooltip}]]]
        {method} + regrid_snow  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\REGRID.m','regrid_snow');{No tooltip}]]]
        {method} + regrid_split  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\REGRID.m','regrid_split');{No tooltip}]]]
        {method} + regrid_split_merge  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\REGRID.m','regrid_split_merge');{possibly better use regrid_split for short timesteps and once}]]]
        {method} + split_cell_extensive  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\REGRID.m','split_cell_extensive');{No tooltip}]]]
        {method} + split_cell_intensive  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\REGRID.m','split_cell_intensive');{No tooltip}]]]
    }
    class SEB <<(H,#E6FFE6)>> [[matlab:matlab.desktop.editor.openAndGoToLine('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\SEB.m',8);{No tooltip}]] {
        ---
        {method} + calculateET  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\SEB.m','calculateET');{No tooltip}]]]
        {method} + calculateET_LAKE  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\SEB.m','calculateET_LAKE');{No tooltip}]]]
        {method} + calculateET_Xice  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\SEB.m','calculateET_Xice');{No tooltip}]]]
        {method} + getET_fraction  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\SEB.m','getET_fraction');{waterC = seb.STATVAR.waterIce ./ seb.STATVAR.layerThick ./ max(1e-20, seb.STATVAR.area); %area can get zero if the area of SNOW CHILD is 100%}]]]
        {method} + getET_fraction_Xice  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\SEB.m','getET_fraction_Xice');{No tooltip}]]]
        {method} + L_star  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\SEB.m','L_star');{No tooltip}]]]
        {method} + latent_heat_evaporation  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\SEB.m','latent_heat_evaporation');{No tooltip}]]]
        {method} + latent_heat_sublimation  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\SEB.m','latent_heat_sublimation');{No tooltip}]]]
        {method} + penetrate_SW_no_transmission  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\SEB.m','penetrate_SW_no_transmission');{No tooltip}]]]
        {method} + penetrate_SW_transmission_bulk  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\SEB.m','penetrate_SW_transmission_bulk');{S_up and S_down can in principle be spectrally resolved when provided as}]]]
        {method} + penetrate_SW_transmission_spectral  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\SEB.m','penetrate_SW_transmission_spectral');{S_up and S_down are spectrally resolved when provided as}]]]
        {method} + psi_H  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\SEB.m','psi_H');{No tooltip}]]]
        {method} + psi_M  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\SEB.m','psi_M');{No tooltip}]]]
        {method} + Q_eq  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\SEB.m','Q_eq');{No tooltip}]]]
        {method} + Q_eq_potET  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\SEB.m','Q_eq_potET');{No tooltip}]]]
        {method} + Q_h  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\SEB.m','Q_h');{No tooltip}]]]
        {method} + rho_air  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\SEB.m','rho_air');{No tooltip}]]]
        {method} + satPresIce  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\SEB.m','satPresIce');{No tooltip}]]]
        {method} + satPresWater  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\SEB.m','satPresWater');{No tooltip}]]]
    }
    class SNOW <<(H,#E6FFE6)>> [[matlab:matlab.desktop.editor.openAndGoToLine('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\SNOW.m',7);{No tooltip}]] {
        ---
        {method} + advance_prognostic_new_snow_CHILD_crocus  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\SNOW.m','advance_prognostic_new_snow_CHILD_crocus');{No tooltip}]]]
        {method} + advance_prognostic_new_snow_crocus  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\SNOW.m','advance_prognostic_new_snow_crocus');{No tooltip}]]]
        {method} + calculate_albedo_crocus  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\SNOW.m','calculate_albedo_crocus');{No tooltip}]]]
        {method} + calculate_albedo_simple  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\SNOW.m','calculate_albedo_simple');{No tooltip}]]]
        {method} + compaction  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\SNOW.m','compaction');{No tooltip}]]]
        {method} + get_boundary_condition_allSNOW_rain_u  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\SNOW.m','get_boundary_condition_allSNOW_rain_u');{No tooltip}]]]
        {method} + get_boundary_condition_allSNOW_u  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\SNOW.m','get_boundary_condition_allSNOW_u');{No tooltip}]]]
        {method} + get_boundary_condition_SNOW_u  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\SNOW.m','get_boundary_condition_SNOW_u');{No tooltip}]]]
        {method} + get_snow_properties_crocus  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\SNOW.m','get_snow_properties_crocus');{No tooltip}]]]
        {method} + get_sublimation  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\SNOW.m','get_sublimation');{No tooltip}]]]
        {method} + get_T_gradient_snow  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\SNOW.m','get_T_gradient_snow');{No tooltip}]]]
        {method} + get_T_gradient_snow_single_cell  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\SNOW.m','get_T_gradient_snow_single_cell');{No tooltip}]]]
        {method} + get_timestep_SNOW  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\SNOW.m','get_timestep_SNOW');{No tooltip}]]]
        {method} + get_timestep_SNOW_CHILD  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\SNOW.m','get_timestep_SNOW_CHILD');{timestep = (-snow.STATVAR.energy ./ snow.TEMP.d_energy) .* double(snow.TEMP.d_energy>0) + double(snow.TEMP.d_energy<=0).*snow.PARA.dt_max;}]]]
        {method} + get_timestep_SNOW_mass_balance  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\SNOW.m','get_timestep_SNOW_mass_balance');{No tooltip}]]]
        {method} + get_timestep_SNOW_sublimation  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\SNOW.m','get_timestep_SNOW_sublimation');{No tooltip}]]]
        {method} + initialize_zero_snow_BASE  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\SNOW.m','initialize_zero_snow_BASE');{No tooltip}]]]
        {method} + make_SNOW_CHILD  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\SNOW.m','make_SNOW_CHILD');{No tooltip}]]]
        {method} + prog_metamorphism  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\SNOW.m','prog_metamorphism');{No tooltip}]]]
        {method} + prog_wind_drift  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\SNOW.m','prog_wind_drift');{No tooltip}]]]
        {method} + subtract_water  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\SNOW.m','subtract_water');{No tooltip}]]]
        {method} + subtract_water2  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\SNOW.m','subtract_water2');{No tooltip}]]]
        {method} + subtract_water_CHILD  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\SNOW.m','subtract_water_CHILD');{No tooltip}]]]
        {method} + subtract_water_CHILD2  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\SNOW.m','subtract_water_CHILD2');{No tooltip}]]]
    }
    class SNOW_FLUXES_LATERAL <<(H,#E6FFE6)>> [[matlab:matlab.desktop.editor.openAndGoToLine('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\SNOW_FLUXES_LATERAL.m',9);{No tooltip}]] {
        ---
        {method} + lateral3D_pull_snow_crocus  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\SNOW_FLUXES_LATERAL.m','lateral3D_pull_snow_crocus');{No tooltip}]]]
        {method} + lateral3D_push_snow_crocus  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\SNOW_FLUXES_LATERAL.m','lateral3D_push_snow_crocus');{No tooltip}]]]
        {method} + lateral3D_push_snow_crocus2  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\SNOW_FLUXES_LATERAL.m','lateral3D_push_snow_crocus2');{No tooltip}]]]
    }
    class SNOW_crocus_bucketW_seb <<(H,#E6FFE6)>> [[matlab:matlab.desktop.editor.openAndGoToLine('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m',10);{No tooltip}]] {
        {field} + PARENT [[[matlab:matlab.desktop.editor.openAndGoToLine('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m',13);{No tooltip}]]]
        ---
        {method} + advance_prognostic  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m','advance_prognostic');{No tooltip}]]]
        {method} + advance_prognostic_CHILD  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m','advance_prognostic_CHILD');{No tooltip}]]]
        {method} + check_trigger  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m','check_trigger');{No tooltip}]]]
        {method} + compute_diagnostic  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m','compute_diagnostic');{No tooltip}]]]
        {method} + compute_diagnostic_CHILD  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m','compute_diagnostic_CHILD');{No tooltip}]]]
        {method} + compute_diagnostic_first_cell  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m','compute_diagnostic_first_cell');{No tooltip}]]]
        {method} + conductivity  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m','conductivity');{No tooltip}]]]
        {method} + conductivity_snow_Yen  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m','conductivity_snow_Yen');{No tooltip}]]]
        {method} + finalize_init  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m','finalize_init');{No tooltip}]]]
        {method} + get_boundary_condition_allSNOW_rain_u  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m','get_boundary_condition_allSNOW_rain_u');{No tooltip}]]]
        {method} + get_boundary_condition_allSNOW_u  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m','get_boundary_condition_allSNOW_u');{No tooltip}]]]
        {method} + get_boundary_condition_l  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m','get_boundary_condition_l');{No tooltip}]]]
        {method} + get_boundary_condition_SNOW_u  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m','get_boundary_condition_SNOW_u');{No tooltip}]]]
        {method} + get_boundary_condition_u  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m','get_boundary_condition_u');{No tooltip}]]]
        {method} + get_boundary_condition_u_CHILD  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m','get_boundary_condition_u_CHILD');{No tooltip}]]]
        {method} + get_boundary_condition_u_create_CHILD  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m','get_boundary_condition_u_create_CHILD');{No tooltip}]]]
        {method} + get_derivative_energy  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m','get_derivative_energy');{No tooltip}]]]
        {method} + get_derivatives_prognostic  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m','get_derivatives_prognostic');{No tooltip}]]]
        {method} + get_derivatives_prognostic_CHILD  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m','get_derivatives_prognostic_CHILD');{No tooltip}]]]
        {method} + get_saturated_hardBottom_first_cell  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m','get_saturated_hardBottom_first_cell');{No tooltip}]]]
        {method} + get_T_water_freeW  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m','get_T_water_freeW');{No tooltip}]]]
        {method} + get_timestep  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m','get_timestep');{No tooltip}]]]
        {method} + get_timestep_CHILD  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m','get_timestep_CHILD');{No tooltip}]]]
        {method} + get_timestep_heat_coduction  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m','get_timestep_heat_coduction');{No tooltip}]]]
        {method} + get_timestep_SNOW_CHILD  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m','get_timestep_SNOW_CHILD');{No tooltip}]]]
        {method} + get_timestep_SNOW_mass_balance  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m','get_timestep_SNOW_mass_balance');{No tooltip}]]]
        {method} + initialize_zero_snow_BASE  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m','initialize_zero_snow_BASE');{No tooltip}]]]
        {method} + L_star  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m','L_star');{No tooltip}]]]
        {method} + lateral3D_pull_heat  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m','lateral3D_pull_heat');{No tooltip}]]]
        {method} + lateral3D_pull_snow  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m','lateral3D_pull_snow');{No tooltip}]]]
        {method} + lateral3D_pull_water_unconfined_aquifer  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m','lateral3D_pull_water_unconfined_aquifer');{No tooltip}]]]
        {method} + lateral3D_push_heat  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m','lateral3D_push_heat');{No tooltip}]]]
        {method} + lateral3D_push_snow  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m','lateral3D_push_snow');{No tooltip}]]]
        {method} + lateral3D_push_water_unconfined_aquifer  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m','lateral3D_push_water_unconfined_aquifer');{No tooltip}]]]
        {method} + lateral_push_remove_surfaceWater  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m','lateral_push_remove_surfaceWater');{No tooltip}]]]
        {method} + lateral_push_remove_water_seepage  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m','lateral_push_remove_water_seepage');{No tooltip}]]]
        {method} + lateral_push_water_reservoir  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m','lateral_push_water_reservoir');{No tooltip}]]]
        {method} + make_SNOW_CHILD  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m','make_SNOW_CHILD');{No tooltip}]]]
        {method} + penetrate_SW  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m','penetrate_SW');{No tooltip}]]]
        {method} + penetrate_SW_transmission_spectral  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m','penetrate_SW_transmission_spectral');{No tooltip}]]]
        {method} + provide_CONST  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m','provide_CONST');{No tooltip}]]]
        {method} + provide_PARA  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m','provide_PARA');{No tooltip}]]]
        {method} + provide_STATVAR  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m','provide_STATVAR');{No tooltip}]]]
        {method} + Q_eq_potET  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m','Q_eq_potET');{No tooltip}]]]
        {method} + Q_h  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m','Q_h');{No tooltip}]]]
        {method} + regrid_snow  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m','regrid_snow');{No tooltip}]]]
        {method} + subtract_water  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m','subtract_water');{No tooltip}]]]
        {method} + subtract_water_CHILD  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m','subtract_water_CHILD');{No tooltip}]]]
        {method} + surface_energy_balance  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_2_full_classes\SNOW_crocus_bucketW_seb.m','surface_energy_balance');{No tooltip}]]]
    }
    class WATER_FLUXES <<(H,#E6FFE6)>> [[matlab:matlab.desktop.editor.openAndGoToLine('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES.m',6);{No tooltip}]] {
        ---
        {method} + calculate_hydraulicConductivity  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES.m','calculate_hydraulicConductivity');{No tooltip}]]]
        {method} + calculate_hydraulicConductivity_RichardsEq  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES.m','calculate_hydraulicConductivity_RichardsEq');{No tooltip}]]]
        {method} + calculate_hydraulicConductivity_RichardsEq_Xice  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES.m','calculate_hydraulicConductivity_RichardsEq_Xice');{No tooltip}]]]
        {method} + calculate_hydraulicConductivity_SNOW  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES.m','calculate_hydraulicConductivity_SNOW');{No tooltip}]]]
        {method} + calculate_hydraulicConductivity_Xice  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES.m','calculate_hydraulicConductivity_Xice');{No tooltip}]]]
        {method} + get_boundary_condition_l_water2  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES.m','get_boundary_condition_l_water2');{No tooltip}]]]
        {method} + get_boundary_condition_u_RichardsEq  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES.m','get_boundary_condition_u_RichardsEq');{No tooltip}]]]
        {method} + get_boundary_condition_u_water2  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES.m','get_boundary_condition_u_water2');{No tooltip}]]]
        {method} + get_boundary_condition_u_water_LAKE  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES.m','get_boundary_condition_u_water_LAKE');{No tooltip}]]]
        {method} + get_boundary_condition_u_water_LAKE_frozen  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES.m','get_boundary_condition_u_water_LAKE_frozen');{No tooltip}]]]
        {method} + get_boundary_condition_u_water_RichardsEq_Xice  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES.m','get_boundary_condition_u_water_RichardsEq_Xice');{No tooltip}]]]
        {method} + get_boundary_condition_u_water_SNOW  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES.m','get_boundary_condition_u_water_SNOW');{No tooltip}]]]
        {method} + get_boundary_condition_u_water_Xice  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES.m','get_boundary_condition_u_water_Xice');{No tooltip}]]]
        {method} + get_derivative_water2  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES.m','get_derivative_water2');{No tooltip}]]]
        {method} + get_derivative_water_RichardsEq  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES.m','get_derivative_water_RichardsEq');{No tooltip}]]]
        {method} + get_derivative_water_RichardsEq_Xice  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES.m','get_derivative_water_RichardsEq_Xice');{No tooltip}]]]
        {method} + get_derivative_water_SNOW  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES.m','get_derivative_water_SNOW');{No tooltip}]]]
        {method} + get_derivative_water_Xice  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES.m','get_derivative_water_Xice');{No tooltip}]]]
        {method} + get_derivative_Xwater  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES.m','get_derivative_Xwater');{saturation = ground.STATVAR.Xwater ./ ground.STATVAR.area ./ (ground.PARA.hydraulicConductivity .* ground.PARA.dt_max);}]]]
        {method} + get_timestep_water  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES.m','get_timestep_water');{outflow + inflow}]]]
        {method} + get_timestep_water_RichardsEq  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES.m','get_timestep_water_RichardsEq');{no negative values and no overtopping}]]]
        {method} + get_timestep_water_RichardsEq_Xice  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES.m','get_timestep_water_RichardsEq_Xice');{no negative values and no overtopping}]]]
        {method} + get_timestep_water_SNOW  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES.m','get_timestep_water_SNOW');{outflow + inflow}]]]
        {method} + get_timestep_water_Xice  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES.m','get_timestep_water_Xice');{outflow + inflow}]]]
        {method} + get_timestep_Xwater  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES.m','get_timestep_Xwater');{only outflow}]]]
        {method} + reduction_factor_in  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES.m','reduction_factor_in');{No tooltip}]]]
        {method} + reduction_factor_out  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES.m','reduction_factor_out');{No tooltip}]]]
    }
    class WATER_FLUXES_LATERAL <<(H,#E6FFE6)>> [[matlab:matlab.desktop.editor.openAndGoToLine('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES_LATERAL.m',8);{No tooltip}]] {
        ---
        {method} + get_saturated_hardBottom_first_cell_lake_unfrozen  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES_LATERAL.m','get_saturated_hardBottom_first_cell_lake_unfrozen');{No tooltip}]]]
        {method} + get_saturated_hardBottom_first_cell_simple  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES_LATERAL.m','get_saturated_hardBottom_first_cell_simple');{No tooltip}]]]
        {method} + get_saturated_hardBottom_first_cell_snow  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES_LATERAL.m','get_saturated_hardBottom_first_cell_snow');{No tooltip}]]]
        {method} + get_saturated_hardBottom_first_cell_Xice  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES_LATERAL.m','get_saturated_hardBottom_first_cell_Xice');{No tooltip}]]]
        {method} + lateral3D_pull_water_general_aquifer_simple  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES_LATERAL.m','lateral3D_pull_water_general_aquifer_simple');{No tooltip}]]]
        {method} + lateral3D_pull_water_unconfined_aquifer_lake_unfrozen  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES_LATERAL.m','lateral3D_pull_water_unconfined_aquifer_lake_unfrozen');{No tooltip}]]]
        {method} + lateral3D_pull_water_unconfined_aquifer_simple  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES_LATERAL.m','lateral3D_pull_water_unconfined_aquifer_simple');{No tooltip}]]]
        {method} + lateral3D_pull_water_unconfined_aquifer_snow  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES_LATERAL.m','lateral3D_pull_water_unconfined_aquifer_snow');{No tooltip}]]]
        {method} + lateral3D_pull_water_unconfined_aquifer_Xice  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES_LATERAL.m','lateral3D_pull_water_unconfined_aquifer_Xice');{No tooltip}]]]
        {method} + lateral3D_push_water_general_aquifer_simple  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES_LATERAL.m','lateral3D_push_water_general_aquifer_simple');{move bottom up and allocate excess water to next cell}]]]
        {method} + lateral3D_push_water_unconfined_aquifer_lake_unfrozen  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES_LATERAL.m','lateral3D_push_water_unconfined_aquifer_lake_unfrozen');{move bottom up and allocate excess water to next cell}]]]
        {method} + lateral3D_push_water_unconfined_aquifer_simple  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES_LATERAL.m','lateral3D_push_water_unconfined_aquifer_simple');{move bottom up and allocate excess water to next cell}]]]
        {method} + lateral3D_push_water_unconfined_aquifer_snow  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES_LATERAL.m','lateral3D_push_water_unconfined_aquifer_snow');{move bottom up and allocate excess water to next cell}]]]
        {method} + lateral3D_push_water_unconfined_aquifer_snow2  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES_LATERAL.m','lateral3D_push_water_unconfined_aquifer_snow2');{move bottom up and allocate excess water to next cell}]]]
        {method} + lateral3D_push_water_unconfined_aquifer_Xice  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES_LATERAL.m','lateral3D_push_water_unconfined_aquifer_Xice');{move bottom up and allocate excess water to next cell}]]]
        {method} + lateral_push_remove_subsurfaceWater_simple  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES_LATERAL.m','lateral_push_remove_subsurfaceWater_simple');{No tooltip}]]]
        {method} + lateral_push_remove_surfaceWater_simple  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES_LATERAL.m','lateral_push_remove_surfaceWater_simple');{No tooltip}]]]
        {method} + lateral_push_remove_surfaceWater_Xice  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES_LATERAL.m','lateral_push_remove_surfaceWater_Xice');{No tooltip}]]]
        {method} + lateral_push_remove_water_seepage_simple  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES_LATERAL.m','lateral_push_remove_water_seepage_simple');{No tooltip}]]]
        {method} + lateral_push_remove_water_seepage_snow  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES_LATERAL.m','lateral_push_remove_water_seepage_snow');{No tooltip}]]]
        {method} + lateral_push_remove_water_seepage_Xice  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES_LATERAL.m','lateral_push_remove_water_seepage_Xice');{No tooltip}]]]
        {method} + lateral_push_water_reservoir_lake_unfrozen  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES_LATERAL.m','lateral_push_water_reservoir_lake_unfrozen');{water removed and added instantaneously}]]]
        {method} + lateral_push_water_reservoir_RichardsEq_Xice  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES_LATERAL.m','lateral_push_water_reservoir_RichardsEq_Xice');{No tooltip}]]]
        {method} + lateral_push_water_reservoir_simple  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES_LATERAL.m','lateral_push_water_reservoir_simple');{No tooltip}]]]
        {method} + lateral_push_water_reservoir_snow  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES_LATERAL.m','lateral_push_water_reservoir_snow');{No tooltip}]]]
        {method} + lateral_push_water_reservoir_Xice  [[[matlab:matlab.desktop.editor.openAndGoToFunction('C:\thin\02_Code\Matlab\CryoGRID\202008_CryoGrid_NewOOP_GIT_CURRENT_THIN\modules\TIER_1_processes\WATER_FLUXES_LATERAL.m','lateral_push_water_reservoir_Xice');{No tooltip}]]]
    }
    BASE <|-- HEAT_CONDUCTION
    BASE <|-- HEAT_FLUXES_LATERAL
    BASE <|-- REGRID
    BASE <|-- SEB
    BASE <|-- SNOW
    BASE <|-- SNOW_FLUXES_LATERAL
    SEB <|-- SNOW_crocus_bucketW_seb
    HEAT_CONDUCTION <|-- SNOW_crocus_bucketW_seb
    WATER_FLUXES <|-- SNOW_crocus_bucketW_seb
    HEAT_FLUXES_LATERAL <|-- SNOW_crocus_bucketW_seb
    WATER_FLUXES_LATERAL <|-- SNOW_crocus_bucketW_seb
    SNOW <|-- SNOW_crocus_bucketW_seb
    SNOW_FLUXES_LATERAL <|-- SNOW_crocus_bucketW_seb
    REGRID <|-- SNOW_crocus_bucketW_seb
    BASE <|-- WATER_FLUXES
    BASE <|-- WATER_FLUXES_LATERAL
@enduml
